version: "3.8"
services:
  ui:
    build: ./ui
    ports:
      - 3000:3000
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - REACT_APP_RUN_FROM_DC_URL=https://jsonplaceholder.typicode.com