export const ROUTE_CONSTANTS = {
  ROOT: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
};

export const STRINGS = {
  /** Login page */
  NEUTRON: "Neutron",
  LOGIN_PAGE_TITLE: "Login",
  LOGIN_PAGE_CONTENT: "Please sign-in to your account and start the Legalism",
  SIGNUP_PAGE_TITLE: "Sign Up",
  SIGNUP_PAGE_CONTENT: "Enter your username password details",
  SIGN_IN: "Sign In",
  SIGN_UP: "Sign Up",
  FORGOT_PASSWORD: "Forgot Password",
  READ_AND_AGREE_TO: "I have read and agree to ",
  TERMS_AND_CONDITIONS: "Terms & Conditions",
  CREATE_AN_ACCOUNT: "Create an account",
  HAVE_AN_ACCOUNT: "Do you have an account?",
  SIGN_UP_EXM: "Sign Up!",
  ALREADY_HAVE_AN_ACCOUNT: "Already have an account?",
  SIGN_IN_EXM: "Sign In!",
  ENTER_YOUR_EMAIL: "Email ID",
  ENTER_PASSWORD: "Enter Password",
  CONFIRM_PASSWORD: "Confirm Password",
  NEW_PASSWORD: "New Password",
  LOGIN_TO_ACCOUNT: "Login",
  CREATE_ACCOUNT: "Create Account",
  FIRST_NAME: "Name",
  LAST_NAME: "Last Name",
  ABOUT_US: "About Us",
  CONTACT_US: "Contact Us",
  PRIVACY_POLICY: "Privacy Policy",
  COPYRIGHT: "Copyright © 2021 Neutron",
  CONFIRM: "Confirm",
  RESEND_OTP: "Resend OTP",
  OTP_SCREEN_TITLE: "Enter OTP",
  OTP_SENT_LINE_1: `We’ve sent a verification code to your email.`,
  OTP_SENT_LINE_2: ` Enter the code from your email in the field below.`,
  PHONE_AND_EMAIL: "Phone Number and Email Address",
  PHONE_NUMBER: "Phone Number",
  COMPANY_NAME: "Username",
  COUNTRY: "Country",
  START_TRIAL: "Create Account",
  SEE_PLANS: "See Plans",
  FORGOT_PWD_SUBTITLE:
    "Don’t worry! It happens. Please enter the email address associated with your account.",
  BACK_TO_SIGN_IN: "Back to Sign In",
  EMAIL_ADDRESS: "Email Address",
  CREATE_PASSWORD: "Reset Password",
  RESET_PWD_SUBTITLE: "Reset your password to access your Legitron portal",
  PASSWORD_RESET_CODE: "Password Reset Code",
  UPDATE_PASSWORD: "Update Password",
  LOGOUT: "Logout",
  COMING_SOON: "Coming Soon!",
  SKIP: "Skip",
  UPLOAD_AGREEMENT: "Upload Agreement",
  SUBMIT: "Submit",
  AGREEMENT_NAME: "Agreement Name",
  AGREEMENT_TYPE: "Type of Agreement",
  AGREEMNET_DATE: "Select Date (To - From)",
  REASON_FOR_RETURN_REVIEWER: "Please add reason",
  SHARE_TO_VENDOR: "Please write email",
  PLACEHOLDER_VENDOR: "⚉ ⚉ ⚉ ⚉ ⚉ ⚉ ⚉ ",
  ESIGN_PROCESS: "Please enter details for e-sign process",
};

export const INPUT_FIELD_NAMES = {
  EMAIL: "email",
  PASSWORD: "password"
};

export const VALIDATION_MSGS = {
  TOO_LONG: "Too Long!",
  TOO_SHORT: "Too Short!",
  OTP_CODE_LENGTH: "Must be 6 digits.",
  INVALID_EMAIL: "Invalid email.",
  REQUIRED: "Required.",
  INVALID_PHONENO: "Invalid phone number.",
  INVALID_CODE: "Invalid code.",
  PASSWORD_MISMATCH: "Passwords must match",
  PASSWORD_PATTERN_INVALID:
    "Use a combination of uppercase, lowercase, digits and specical characters.",
};